# Generated by Django 3.0 on 2019-12-12 18:00

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, verbose_name='Job type')),
                ('url', models.CharField(max_length=200, verbose_name='Job url')),
                ('title', models.CharField(max_length=200, verbose_name='Job title')),
                ('description', models.TextField(max_length=200, verbose_name='Job description')),
                ('how_to_apply', models.TextField(max_length=200, verbose_name='Job applying')),
                ('company', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='companies.Companies')),
            ],
        ),
    ]
