# Generated by Django 3.0 on 2019-12-12 17:03

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('numeAplicatie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('website', models.CharField(max_length=200, verbose_name='Website')),
                ('location', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='numeAplicatie.Location')),
            ],
        ),
    ]
